# Generated by Django 3.1.2 on 2021-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_purchase_exam_bank_record',
            name='is_preorder',
            field=models.BooleanField(default=True),
        ),
    ]
