# Generated by Django 3.1.2 on 2021-01-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_owing_teacher_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_auth_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('lesson_id', models.IntegerField()),
                ('lesson_booking_info_id', models.IntegerField()),
                ('owing_minutes', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '學生積欠時數',
                'verbose_name_plural': '學生積欠時數',
                'ordering': ['-created_time'],
            },
        ),
        migrations.RemoveField(
            model_name='student_remaining_minutes_of_each_purchased_lesson_set',
            name='lesson_booking_info_ids',
        ),
    ]
