# Generated by Django 3.1.5 on 2021-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_finance', '0002_auto_20210318_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_purchase_exam_bank_record',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='user_purchase_exam_bank_record',
            name='when_is_remittance_confirmed_by_quikok',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_purchase_exam_bank_record',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_purchase_exam_bank_record',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
