# Generated by Django 3.1.5 on 2021-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_finance', '0003_auto_20210318_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_purchase_record',
            options={'ordering': ['-updated_time'], 'verbose_name': '學生購買課程紀錄', 'verbose_name_plural': '學生購買課程紀錄'},
        ),
        migrations.AlterModelOptions(
            name='user_purchase_exam_bank_record',
            options={'ordering': ['-updated_time'], 'verbose_name': '題庫預購紀錄', 'verbose_name_plural': '題庫預購紀錄'},
        ),
    ]
