# Generated by Django 3.1.5 on 2021-03-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_history_Mr_Q2user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_info_system2user_id', models.IntegerField()),
                ('user_auth_id', models.IntegerField()),
                ('system_user_auth_id', models.IntegerField()),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=30)),
                ('who_is_sender', models.CharField(max_length=20)),
                ('sender_auth_id', models.IntegerField()),
                ('system_is_read', models.BooleanField(default=False)),
                ('user_is_read', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='chat_history_user2user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_info_user2user_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('student_auth_id', models.IntegerField()),
                ('parent_auth_id', models.IntegerField()),
                ('message', models.TextField()),
                ('message_type', models.CharField(max_length=30)),
                ('who_is_sender', models.CharField(max_length=20)),
                ('sender_auth_id', models.IntegerField()),
                ('student_is_read', models.BooleanField(default=False)),
                ('teacher_is_read', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='chat_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_set', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chatroom_info_Mr_Q2user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_auth_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=20)),
                ('system_user_auth_id', models.IntegerField()),
                ('chatroom_type', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='chatroom_info_user2user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_auth_id', models.IntegerField()),
                ('student_auth_id', models.IntegerField()),
                ('parent_auth_id', models.IntegerField()),
                ('chatroom_type', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='default_notifications_from_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_which_chatroom', models.CharField(max_length=20)),
                ('notification_code', models.CharField(max_length=20)),
                ('notification_context', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.chat_room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
