# Generated by Django 2.0.4 on 2020-08-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_room',
            old_name='member1',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='chat_room',
            old_name='member2',
            new_name='teacher',
        ),
    ]
