# Generated by Django 3.1.5 on 2021-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info',
            name='main_picture',
            field=models.ImageField(default='articles/default_main_picture.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='author_profile',
            name='thumbnail',
            field=models.ImageField(default='authors/default_thumbnail.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploaded_pictures',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
