# Generated by Django 3.1.5 on 2021-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='object_accessed_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=220, null=True)),
                ('url_path', models.CharField(blank=True, max_length=100, null=True)),
                ('api_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=55, null=True)),
                ('object_name', models.CharField(blank=True, max_length=55, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Object Viewed',
                'verbose_name_plural': 'Objects Viewed',
                'ordering': ['-timestamp'],
            },
        ),
    ]
