# Generated by Django 2.0.4 on 2020-09-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('connected_user', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='dev_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('is_male', models.BooleanField()),
                ('date_join', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='general_available_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='specific_available_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('birth_date', models.DateField(null=True)),
                ('is_male', models.BooleanField()),
                ('intro', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('picture_folder', models.ImageField(blank=True, default='snapshop_default.png', upload_to='')),
                ('update_someone_by_email', models.CharField(max_length=405)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40)),
                ('birth_date', models.DateField(null=True)),
                ('is_male', models.BooleanField()),
                ('intro', models.CharField(max_length=150)),
                ('highlight_1', models.CharField(max_length=10)),
                ('highlight_2', models.CharField(max_length=10)),
                ('highlight_3', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=12)),
                ('picture_folder', models.ImageField(blank=True, default='snapshop_default.png', upload_to='')),
                ('tutor_exp_in_years', models.FloatField(default=0.0)),
                ('student_type', models.CharField(max_length=400)),
                ('subject_type', models.CharField(max_length=400)),
                ('id_cert', models.CharField(max_length=150)),
                ('education_1', models.CharField(max_length=60)),
                ('education_2', models.CharField(max_length=60)),
                ('education_3', models.CharField(max_length=60)),
                ('education_cert_1', models.CharField(max_length=150)),
                ('education_cert_2', models.CharField(max_length=150)),
                ('education_cert_3', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=60)),
                ('occupation_cert', models.CharField(max_length=150)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='specific_available_time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_time', to='account.teacher_profile'),
        ),
        migrations.AddField(
            model_name='general_available_time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_time', to='account.teacher_profile'),
        ),
    ]
