# Generated by Django 3.0.8 on 2020-07-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('connected_user', models.CharField(max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('nickname', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('is_male', models.BooleanField()),
                ('role', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('picture_folder', models.CharField(max_length=150)),
                ('tracking_mobile', models.CharField(max_length=130)),
                ('update_someone_by_email', models.CharField(max_length=405)),
                ('update_someone_by_mobile', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191)),
                ('nickname', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('is_male', models.BooleanField()),
                ('intro', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=12)),
                ('picture_folder', models.CharField(max_length=150)),
                ('tutor_exp_in_years', models.FloatField(default=0.0)),
                ('student_type', models.CharField(max_length=400)),
                ('subject_type', models.CharField(max_length=400)),
                ('id_cert', models.CharField(max_length=150)),
                ('education_1', models.CharField(max_length=60)),
                ('education_2', models.CharField(max_length=60)),
                ('education_3', models.CharField(max_length=60)),
                ('education_cert_1', models.CharField(max_length=150)),
                ('education_cert_2', models.CharField(max_length=150)),
                ('education_cert_3', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=60)),
                ('occupation_cert', models.CharField(max_length=150)),
            ],
        ),
    ]
