# Generated by Django 2.0.4 on 2020-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor_profile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
