# Generated by Django 3.1.5 on 2021-05-17 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210506_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation_code_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('detail', models.TextField(blank=True, default='', null=True)),
                ('expiration_date', models.DateField(blank=True, default=datetime.datetime(2999, 12, 31, 0, 0), null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_invitation_code_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=20)),
                ('invitation_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
