# Generated by Django 2.0.4 on 2020-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200814_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
