# Generated by Django 3.0.8 on 2020-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200819_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='picture_folder',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
