# Generated by Django 3.1.5 on 2021-05-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_invitation_code_detail_user_invitation_code_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='upload_picture_1_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='upload_picture_2_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='upload_picture_3_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='upload_picture_4_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='upload_picture_5_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='youtube_video_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
