# Generated by Django 2.0.4 on 2020-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200818_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
