# Generated by Django 3.1.5 on 2021-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_bank_sales_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(default='', max_length=30)),
                ('selling_price', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '題庫販售方案',
                'verbose_name_plural': '題庫販售方案',
                'ordering': ['-updated_time'],
            },
        ),
    ]
