# Generated by Django 3.1.2 on 2020-11-11 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson_booking_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('student_auth_id', models.IntegerField()),
                ('parent_auth_id', models.IntegerField()),
                ('booked_by', models.CharField(max_length=20)),
                ('last_changed_by', models.CharField(max_length=20)),
                ('booking_set', models.IntegerField()),
                ('remaining_minutes', models.TimeField()),
                ('booking_date_and_time', models.CharField(max_length=400)),
                ('booking_status', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='lesson_sales_sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('price_per_hour', models.IntegerField()),
                ('sales_set', models.CharField(max_length=20)),
                ('total_hours_of_the_sales_set', models.IntegerField()),
                ('total_amount_of_the_sales_set', models.IntegerField()),
                ('price_per_hour_after_discount', models.IntegerField()),
                ('selling_volume', models.IntegerField()),
                ('taking_lesson_volume', models.IntegerField()),
                ('fulfilled_volume', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_sold_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson_reviews',
            name='picture_folder',
        ),
        migrations.AddField(
            model_name='lesson_info',
            name='edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lesson_reviews',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_reviews',
            name='edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson_card',
            name='background_picture_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson_card',
            name='teacher_thumbnail_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='background_picture_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='lesson_attributes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='lesson_info_snapshot',
        ),
    ]
