# Generated by Django 3.1.5 on 2021-03-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_info_for_users_not_signed_up',
            name='discount_price',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
