# Generated by Django 3.1.5 on 2021-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson_card',
            options={'verbose_name': '課程資訊-小卡', 'verbose_name_plural': '課程資訊-小卡'},
        ),
        migrations.AlterModelOptions(
            name='lesson_info',
            options={'ordering': ['-created_time'], 'verbose_name': '課程資訊-詳細', 'verbose_name_plural': '課程資訊-詳細'},
        ),
        migrations.AddField(
            model_name='lesson_card',
            name='lesson_ranking_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson_info',
            name='lesson_ranking_score',
            field=models.IntegerField(default=0),
        ),
    ]
