# Generated by Django 3.1.2 on 2021-01-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson_reviews_from_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corresponding_lesson_id', models.IntegerField()),
                ('corresponding_lesson_booking_info_id', models.IntegerField()),
                ('student_auth_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('score_given', models.IntegerField(blank=True, null=True)),
                ('is_teacher_late_for_lesson', models.BooleanField(blank=True, null=True)),
                ('is_teacher_being_frivolous_in_lesson', models.BooleanField(blank=True, null=True)),
                ('is_teacher_incapabale', models.BooleanField(blank=True, null=True)),
                ('remark_given', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '學生對課程評價',
                'verbose_name_plural': '學生對課程評價',
            },
        ),
        migrations.CreateModel(
            name='student_reviews_from_teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corresponding_lesson_id', models.IntegerField()),
                ('corresponding_lesson_booking_info_id', models.IntegerField()),
                ('student_auth_id', models.IntegerField()),
                ('teacher_auth_id', models.IntegerField()),
                ('score_given', models.IntegerField(blank=True, null=True)),
                ('is_student_late_for_lesson', models.BooleanField(blank=True, null=True)),
                ('is_student_being_frivolous_in_lesson', models.BooleanField(blank=True, null=True)),
                ('is_student_or_parents_not_friendly', models.BooleanField(blank=True, null=True)),
                ('remark_given', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '老師對學生評價',
                'verbose_name_plural': '老師對學生評價',
            },
        ),
        migrations.DeleteModel(
            name='lesson_reviews',
        ),
        migrations.RemoveField(
            model_name='lesson_booking_info',
            name='student_remaining_minutes_of_each_purchased_lesson_set_ids',
        ),
        migrations.RemoveField(
            model_name='lesson_completed_record',
            name='teacher_declared_teaching_fee',
        ),
        migrations.AddField(
            model_name='lesson_booking_info',
            name='remark',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson_completed_record',
            name='teacher_declared_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lesson_completed_record',
            name='teacher_declared_start_time',
            field=models.DateTimeField(),
        ),
    ]
