# Generated by Django 3.1.5 on 2021-03-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_info_for_users_not_signed_up_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_info_for_users_not_signed_up',
            name='discount_price',
        ),
    ]
