# Generated by Django 3.1.5 on 2021-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20210317_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_info',
            name='big_title',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='discount_price',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='highlight_1',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='highlight_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='highlight_3',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='how_does_lesson_go',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='lesson_attributes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='lesson_has_one_hour_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='lesson_intro',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='lesson_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='little_title',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='syllabus',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='target_students',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson_info',
            name='trial_class_price',
            field=models.IntegerField(default=-999),
        ),
    ]
