# Generated by Django 3.1.2 on 2021-05-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_auto_20210317_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_info',
            name='hidden_lesson_attributes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
