# Generated by Django 3.1.5 on 2021-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_info_hidden_lesson_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_completed_record',
            name='tuition_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson_sales_sets',
            name='price_per_10_minutes',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
